export PROJECT := vroemvroem

# Environment variable(s) for Symfony
export APP_ENV ?= dev

# Docker permissions (for Linux)
export DOCKER_UID ?= $(shell id -u)
export DOCKER_GID ?= $(shell id -g)
export DOCKER_USER ?= $(DOCKER_UID):$(DOCKER_GID)
